[package]
name = "ynab_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = {version = "1.0.144", features = ["derive"]}
serde_json = "1.0.85"
anyhow = "1.0.65"